# Generated by Django 2.2.7 on 2019-11-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='TODO: Update with a description'),
            preserve_default=False,
        ),
    ]
