# Generated by Django 2.2.7 on 2019-11-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='books',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='users',
            new_name='user',
        ),
    ]
